# Generated by Django 4.2.2 on 2023-06-13 10:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('duration', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message="Duration must be in the format 'MM:SS'.", regex='^\\d{2}:\\d{2}$')], verbose_name='duration')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='review_app.band', verbose_name='band')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
            },
        ),
        migrations.CreateModel(
            name='SongReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000, verbose_name='content')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], default=1, verbose_name='score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_app.song', verbose_name='song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'song review',
                'verbose_name_plural': 'song reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='review_app.songreview', verbose_name='song review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'song review like',
                'verbose_name_plural': 'song review like',
            },
        ),
        migrations.CreateModel(
            name='SongReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('song_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='review_app.songreview', verbose_name='song review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'song review comment',
                'verbose_name_plural': 'song review comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
