# Generated by Django 4.2.2 on 2023-06-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'verbose_name': 'band', 'verbose_name_plural': 'bands'},
        ),
    ]
